site_name: Awesome Cybersecurity Roadmap
site_description: Learn Cybersecurity from Beginner to Advanced
site_author: Aditysinh Rathod
site_url: https://aditysinh-rathod.github.io/awesome-cybersecurity-roadmap/

repo_name: aditysinh-rathod/awesome-cybersecurity-roadmap
repo_url: https://github.com/aditysinh-rathod/awesome-cybersecurity-roadmap

theme:
  name: material
  language: en

  icon:
    repo: fontawesome/brands/github
    logo: material/shield-lock

  palette:
    - scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.top
    - navigation.footer
    - toc.integrate
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji

nav:
  - Home: index.md
